# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'fastSwift App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'NMSSH'
  pod 'TZKeyboardPop'

  # Pods for fastSwift App

  target 'fastSwift AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'fastSwift AppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
